### ISSUE TITLE
PyPi package fails to install and run

### ISSUE THREAD

**Issue by BoltzmannBrain** [IBM/causallib#5] opened 2019-08-14 22:04 UTC
Creating a python 3.6.0 virtual environment and running `pip install causallib` succeeds, but then trying to import any modules fails. E.g. `from causallib.estimation import IPW`:

```
...

~/.pyenv/versions/3.6.0/envs/venv360/lib/python3.6/site-packages/pandas/core/frame.py in <module>
     86 from pandas.core.arrays.datetimelike import DatetimeLikeArrayMixin as DatetimeLikeArray
     87 from pandas.core.arrays.sparse import SparseFrameAccessor
---> 88 from pandas.core.generic import NDFrame, _shared_docs
     89 from pandas.core.index import (
     90     Index,

~/.pyenv/versions/3.6.0/envs/venv360/lib/python3.6/site-packages/pandas/core/generic.py in <module>
     69 from pandas.core.ops import _align_method_FRAME
     70 
---> 71 from pandas.io.formats.format import DataFrameFormatter, format_percentiles
     72 from pandas.io.formats.printing import pprint_thing
     73 from pandas.tseries.frequencies import to_offset

~/.pyenv/versions/3.6.0/envs/venv360/lib/python3.6/site-packages/pandas/io/formats/format.py in <module>
     45 from pandas.core.indexes.datetimes import DatetimeIndex
     46 
---> 47 from pandas.io.common import _expand_user, _stringify_path
     48 from pandas.io.formats.printing import adjoin, justify, pprint_thing
     49 

~/.pyenv/versions/3.6.0/envs/venv360/lib/python3.6/site-packages/pandas/io/common.py in <module>
      7 from http.client import HTTPException  # noqa
      8 from io import BytesIO
----> 9 import lzma
     10 import mmap
     11 import os

~/.pyenv/versions/3.6.0/lib/python3.6/lzma.py in <module>
     25 import io
     26 import os
---> 27 from _lzma import *
     28 from _lzma import _encode_filter_properties, _decode_filter_properties
     29 import _compression

ModuleNotFoundError: No module named '_lzma'
```

It looks like there are versioning issues with pandas.

**Comment by BoltzmannBrain** [comment] 2019-08-14 22:09
Okay downgrading to pandas 0.24.2 solves this. I think 0.25 assumes `lzma` to be available from stdlib, but it's not.

**Comment by yishaishimoni** [comment] 2019-08-15 08:24
Thanks @BoltzmannBrain !
We will update the requirement files as a first quick-fix.
Later we will check if this can be solved to allow pandas 0.25

**Comment by ehudkr** [comment] 2019-08-15 14:00
Hey @BoltzmannBrain, 
first of all, let me congratulate you for opening causallib's first issue! :tada: I don't know about you, but I'm quite excited :blush:

Now, as for the issue itself. I was not able to reproduce the problem using conda environment, so I did some further digging.
It seems to be a recently raised issue in the interface between pyenv and pandas. see:
* https://github.com/pandas-dev/pandas/issues/27543 
* https://github.com/pandas-dev/pandas/issues/27532

Could you please try to simply `import pandas as pd` in your environment? 
If I understood those discussions correctly, it suppose to fail, making it a pandas/pyenv issue rather than a direct causallib one (i.e., it is not caused by how causallib uses pandas, but rather causallib fails to import pandas to begin with. Meaning it would've happen if you were to simply install pandas in your environment, rather than installing it as a causallib dependency).

**Comment by Salompas** [comment] 2019-08-19 16:32
Depending on how Python is installed in your system the module `lzma` will not be available (I first found this after installing Python with `pyenv` on MacOS). This is due to a lack of the appropriate dependencies when compiling Python. 
On release 0.25.1 the issue will be fixed. If your Python is not properly installed (i.e. `lzma` not available) you will get a warning message when importing pandas, but pandas will be imported. However, any function that requires compression via `lzma` will still fail.

**Comment by ehudkr** [comment] 2019-08-20 11:37
Thanks for contributing your bug-fix, @Salompas.
@BoltzmannBrain, feel free to update if this fixes that for you. Unless you or anyone else objects, I think we can close this issue, as it is not directly `causallib` related.

**Comment by BoltzmannBrain** [comment] 2019-08-25 17:03
+1 on @Salompas's assessment. Thank you for addressing the issue!

**Closed** 2019-08-26 07:50 UTC
